import {buildRewardPlan,visibleCheckpoints} from './rewards.js';
import {TiltController,PoseCalibration,TILT_CONFIG,headRoll} from './tilt-controller.js';
function questionId(){return crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint32Array(4)),n=>n.toString(16).padStart(8,'0')).join('')}
const $=s=>document.querySelector(s), app=$('#app'), audio=$('#music');
const paths={home:'m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z',book:'M3 4h7a3 3 0 0 1 2 2 3 3 0 0 1 2-2h7v16h-7a3 3 0 0 0-2 1 3 3 0 0 0-2-1H3z M12 6v15',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',play:'m8 4 12 8-12 8z',music:'M9 18V5l12-3v13 M9 9l12-3 M9 18c0 4-7 4-7 0s7-4 7 0 M21 15c0 4-7 4-7 0s7-4 7 0',volume:'m11 3-6 5H2v8h3l6 5z M15 8a6 6 0 0 1 0 8 M18 4a11 11 0 0 1 0 16',camera:'M3 6h4l2-3h6l2 3h4v15H3z M16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',target:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M12 10v4 M10 12h4',plus:'M12 4v16 M4 12h16',edit:'m4 16 12-12 4 4L8 20H4z M14 6l4 4',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7',copy:'M8 8h13v13H8z M4 16H2V2h14v2',upload:'M12 16V3 m-5 5 5-5 5 5 M3 16v5h18v-5',download:'M12 3v13 m-5-5 5 5 5-5 M3 17v4h18v-4',refresh:'M21 3v6h-6 M3 21v-6h6 M20 9a8 8 0 0 0-14-4 M4 15a8 8 0 0 0 14 4',pause:'M8 4v16 M16 4v16',expand:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',left:'M20 12H4 m7-7-7 7 7 7',right:'M4 12h16 m-7-7 7 7-7 7',star:'m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1z',save:'M3 3h15l3 3v15H3z M7 3v6h10V3 M7 21v-8h10v8',check:'m4 12 5 5L20 6',close:'m5 5 14 14 M19 5 5 19'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.star}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults=[['83 … 84','<','>',0],['25 + 14 = ?','39','41',0],['60 … 56','<','>',1],['18 − 8 = ?','10','12',0],['Số liền sau 49 là…','48','50',1],['7 + 8 = ?','15','16',0],['92 … 89','>','<',0],['36 − 12 = ?','22','24',1],['5 chục bằng…','5','50',1],['40 + 20 = ?','60','70',0]].map((q,i)=>({id:String(i+1),text:q[0],left:q[1],right:q[2],correct:q[3]}));
const defaultSettings={volume:.35,loop:true,effects:true,shuffle:false,seconds:0,threshold:13,hold:700};
let questions=defaults,settings={...defaultSettings};try{const q=JSON.parse(localStorage.getItem('royal-questions'));if(validQuestions(q))questions=q;settings={...defaultSettings,...JSON.parse(localStorage.getItem('royal-settings')||'{}')}}catch{}
let rewardPlan=[],earnedRewards=[],celebrationTimers=[],celebrationEpoch=0,awaitingCenter=false;
let inputMode='tilt',calibrated=false,cameraReady=false,modelReady=false,calibrationTimer=null,calibrationFailed=false,detectFailures=0,modelLoadPromise=null;
const tilt=new TiltController(),poseCalibration=new PoseCalibration();
let detecting=false,lastFaceAt=0,lastDetectError=0,loopEpoch=0;
let view='home',round=[],index=0,score=0,locked=false,feedback='',selected=-1,correctAnswer=false,timer=null,advance=null,remaining=0,musicName='',musicUrl='',musicEnabled=true,stream=null,landmarker=null,cameraState='off',cameraMessage='',raf=0,lastFrame=0,lastVideo=-1,rawAngle=0,baseline=0,hasFace=false,calibrating=false,audioCtx=null,cameraEpoch=0,db=null;
function validQuestions(q){return Array.isArray(q)&&q.length<=300&&q.every(x=>x&&typeof x.text==='string'&&x.text.trim()&&x.text.length<=300&&typeof x.left==='string'&&x.left.trim()&&x.left.length<=150&&typeof x.right==='string'&&x.right.trim()&&x.right.length<=150&&(x.correct===0||x.correct===1))}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').style.display='none',3500)}
function saveSettings(){try{localStorage.setItem('royal-settings',JSON.stringify(settings))}catch{toast('Trình duyệt chưa cho phép lưu thiết lập.')}audio.volume=settings.volume;audio.loop=settings.loop}
function saveQuestions(){try{localStorage.setItem('royal-questions',JSON.stringify(questions));return true}catch{toast('Chưa lưu được. Hãy xuất bộ câu hỏi để giữ lại.');return false}}
function btn(label,action,ic,cls='secondary'){return `<button class="${cls}" data-action="${action}" title="${esc(label)}">${icon(ic)}${label}</button>`}
function scene(){return '<img class="scene" src="./assets/carriage.webp" alt="Cỗ xe bí ngô xanh và vàng trên đường đến cung điện cổ tích">'}
function logo(){return '<img class="game-logo" src="./assets/pumpkin-logo.webp" alt="Bí ngô phép thuật với vương miện">'}
function render(){document.body.dataset.screen=view;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='home')renderHome();if(view==='settings')renderSettings();if(view==='questions')renderQuestions();if(view==='play')renderPlay();if(view==='end')renderEnd();queueFit()}
function go(v){cancelCelebration();audio.pause();clearInterval(timer);clearTimeout(advance);if(!['home','play'].includes(v))stopCamera();view=v;render();window.scrollTo(0,0)}

function mirror(){return `<div class="mirror-column"><div class="magic-mirror"><div class="camera-circle"><video id="video" playsinline muted autoplay ${stream?'':'hidden'}></video><span id="camera-placeholder" ${stream?'hidden':''}>${icon('camera')}<span>Gương thần tiên</span></span></div><img class="mirror-frame" src="./assets/royal-mirror.webp" alt="Khung gương vàng hoàng gia với hoa và lá uốn"><svg class="mirror-hold-ring" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><ellipse cx="50" cy="50" rx="34" ry="33" pathLength="100"/></svg><span class="mirror-spark spark-one" aria-hidden="true">✦</span><span class="mirror-spark spark-two" aria-hidden="true">✧</span></div></div>`}

function attachCamera(){if(stream&&$('#video')){$('#video').srcObject=stream;$('#video').play().catch(()=>{});lastVideo=-1}}
function cameraControls(){return `<div class="camera-controls">${btn('BẬT CAMERA','camera','camera','secondary')}${btn('HIỆU CHỈNH','calibrate','target','secondary')}</div>`}
function canStart(){return inputMode==='touch'||(cameraReady&&modelReady&&calibrated&&!calibrating)}
function updateCameraUI(){
  $('[data-action="mode-tilt"]')?.setAttribute('aria-pressed',inputMode==='tilt');$('[data-action="mode-touch"]')?.setAttribute('aria-pressed',inputMode==='touch');
  $('.setup-lobby')?.classList.toggle('camera-active',cameraState==='loading'||cameraReady);$('.setup-lobby')?.classList.toggle('touch-mode',inputMode==='touch');
  const busy=cameraState==='loading',ready=cameraReady&&modelReady;
  document.querySelectorAll('[data-action="camera"]').forEach(b=>{b.disabled=busy;b.innerHTML=icon(ready?'check':'camera')+(busy?'① ĐANG MỞ…':ready?'① CAMERA ĐÃ BẬT':cameraMessage?'① THỬ LẠI CAMERA':'① BẬT CAMERA');b.title=ready?'Tắt camera':'Bật camera selfie';b.classList.toggle('step-done',ready)});
  document.querySelectorAll('[data-action="calibrate"]').forEach(b=>{b.disabled=!ready||calibrating;b.innerHTML=icon(calibrated?'check':'target')+(calibrating?'② ĐANG HIỆU CHỈNH…':calibrated?'② ĐÃ HIỆU CHỈNH':'② HIỆU CHỈNH');b.classList.toggle('step-done',calibrated)});
  document.querySelectorAll('[data-action="start"]').forEach(b=>{if(view==='home'){b.disabled=!canStart();b.innerHTML=icon('play')+(inputMode==='tilt'?'③ ':'')+'BẮT ĐẦU HÀNH TRÌNH'}});
  const retry=$('[data-action="retry-calibration"]');if(retry)retry.hidden=!calibrationFailed;
  $('.camera-circle')?.classList.toggle('face-found',hasFace);
  if($('#camera-error')){$('#camera-error').textContent=cameraMessage;$('#camera-error').hidden=!cameraMessage}
}


function renderHome(){app.innerHTML=`<section class="setup-lobby"><div class="setup-title"><h1>✨ CỖ XE THẦN TIÊN ✨</h1><p>Cùng tạo nên cỗ xe thần tiên để đến cung điện.</p></div><aside class="pose-guide"><h2>✨ CÁCH CHƠI ✨</h2><div class="poses">${['Chọn đáp án bên trái','Giữ đầu ở giữa','Chọn đáp án bên phải'].map((t,i)=>`<div class="pose"><div class="pose-art pose-${i}" role="img" aria-label="Công chúa ${i===1?'giữ đầu thẳng':i===0?'nghiêng đầu sang trái':'nghiêng đầu sang phải'}"></div><span>${t}</span></div>`).join('')}</div></aside><div class="setup-mirror"><div class="intro-carriage">${scene()}</div>${mirror()}</div><div class="setup-controls"><div id="camera-status" role="status">${inputMode==='touch'?'Chạm đáp án hoặc dùng phím ← →':calibrated?'✨ Đã sẵn sàng! Bắt đầu hành trình thôi!':'Bật camera để mở gương thần tiên'}</div><div id="camera-error" class="camera-error" hidden></div><button class="secondary retry-calibration" data-action="retry-calibration" hidden>🔄 THỬ LẠI</button>${cameraControls()}<div class="mode-choice" role="group" aria-label="Cách chọn đáp án"><button data-action="mode-tilt" aria-pressed="${inputMode==='tilt'}">👸 NGHIÊNG ĐẦU</button><button data-action="mode-touch" aria-pressed="${inputMode==='touch'}">👆 CHẠM</button></div>${btn('BẮT ĐẦU HÀNH TRÌNH','start','play','primary')}</div></section>`;attachCamera();updateCameraUI()}


function renderSettings(){app.innerHTML=`<div class="page-title"><div><div class="eyebrow">Góc của giáo viên</div><h2>Thiết lập trò chơi</h2></div>${btn('Lưu thiết lập','save-settings','save','primary')}</div><div class="two-cols"><section class="panel"><h3>${icon('music')} Nhạc nền</h3><button class="upload" data-action="upload-music">${icon('upload')} ${musicName?esc(musicName):'🎵 THÊM NHẠC NỀN'}</button><p class="muted">MP3, WAV, M4A nếu trình duyệt hỗ trợ.</p><div class="row">${btn('Nghe thử','preview-music','play')}${btn('Tạm dừng','pause-music','pause')}</div><div class="row">${btn('Thay nhạc khác','upload-music','refresh')}${btn('Xóa nhạc','delete-music','trash')}</div><label class="field">Âm lượng <div class="row">${icon('volume')}<input id="volume" type="range" min="0" max="100" value="${Math.round(settings.volume*100)}"><output id="volume-value">${Math.round(settings.volume*100)}%</output></div></label><label class="check"><input type="checkbox" id="loop" ${settings.loop?'checked':''}>Phát lặp lại nhạc nền</label><p class="hint">Nhạc được lưu trên trình duyệt của thiết bị này. Khi đổi câu hỏi, bài nhạc tiếp tục phát.</p></section><section class="panel"><h3>${icon('settings')} Cách chơi</h3><label class="check"><input type="checkbox" id="effects" ${settings.effects?'checked':''}>Bật âm thanh đúng / sai</label><label class="check"><input type="checkbox" id="shuffle" ${settings.shuffle?'checked':''}>Trộn thứ tự câu hỏi</label><label class="field">Thời gian mỗi câu<select id="seconds">${[0,10,15,20,30,60].map(n=>`<option value="${n}" ${settings.seconds===n?'selected':''}>${n?n+' giây':'Không giới hạn'}</option>`).join('')}</select></label><label class="field">Độ nghiêng để chọn<div class="row"><input id="threshold" type="range" min="8" max="25" value="${settings.threshold}"><output id="threshold-value">${settings.threshold}°</output></div></label><label class="field">Giữ đầu nghiêng<select id="hold">${[400,650,700,900,1200].map(n=>`<option value="${n}" ${settings.hold===n?'selected':''}>${n/1000} giây</option>`).join('')}</select></label><p class="hint">Bắt đầu với tư thế thẳng đầu. Dùng nút “Hiệu chỉnh” trong màn chơi khi đổi người chơi hoặc vị trí camera.</p></section></div>`}
function renderQuestions(){app.innerHTML=`<div class="page-title"><div><div class="eyebrow">Chuẩn bị thử thách</div><h2>Bộ câu hỏi <span class="muted">(${questions.length})</span></h2></div>${btn('Thêm câu','add','plus','primary')}</div><div class="row">${btn('Xuất câu hỏi','export','upload')}${btn('Nhập câu hỏi','import','download')}${btn('Bộ Toán mẫu','sample','refresh')}</div><div class="question-list">${questions.map((q,i)=>`<article class="question-row"><span class="qnumber">${String(i+1).padStart(2,'0')}</span><div class="qtext"><strong>${esc(q.text)}</strong><span class="muted">Trái: ${esc(q.left)} ${q.correct===0?'✓':''} &nbsp; · &nbsp; Phải: ${esc(q.right)} ${q.correct===1?'✓':''}</span></div><div class="row"><button class="icon-button" data-edit="${i}" title="Sửa câu hỏi" aria-label="Sửa câu ${i+1}">${icon('edit')}</button><button class="icon-button" data-copy="${i}" title="Nhân bản" aria-label="Nhân bản câu ${i+1}">${icon('copy')}</button><button class="icon-button danger" data-delete="${i}" title="Xóa câu hỏi" aria-label="Xóa câu ${i+1}">${icon('trash')}</button></div></article>`).join('')||'<div class="panel empty">Chưa có câu hỏi. Hãy thêm câu mới hoặc chọn bộ Toán mẫu.</div>'}</div><p class="muted">Câu hỏi được lưu trên trình duyệt này. Xuất bộ câu hỏi để dùng trên thiết bị khác.</p>`}
function editQuestion(i=-1){const q=questions[i]||{text:'',left:'',right:'',correct:0};const d=document.createElement('dialog');d.innerHTML=`<form id="qform"><h3>${i<0?'Thêm':'Sửa'} câu hỏi</h3><label class="field">Nội dung câu hỏi<input name="text" type="text" maxlength="300" required value="${esc(q.text)}"></label><label class="field">Đáp án bên trái<input name="left" type="text" maxlength="150" required value="${esc(q.left)}"></label><label class="field">Đáp án bên phải<input name="right" type="text" maxlength="150" required value="${esc(q.right)}"></label><label class="field">Đáp án đúng<select name="correct"><option value="0" ${q.correct===0?'selected':''}>Bên trái</option><option value="1" ${q.correct===1?'selected':''}>Bên phải</option></select></label><div class="row"><button class="primary" type="submit">${icon('save')} Lưu câu hỏi</button><button class="secondary" type="button" id="cancel-q">Hủy</button></div></form>`;document.body.append(d);d.showModal();d.querySelector('#cancel-q').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),q={id:questionId(),text:f.get('text').trim(),left:f.get('left').trim(),right:f.get('right').trim(),correct:Number(f.get('correct'))};if(!validQuestions([q]))return toast('Vui lòng điền đủ câu hỏi và hai đáp án.');if(i<0){if(questions.length>=300)return toast('Tối đa 300 câu hỏi.');questions.push(q)}else questions[i]=q;saveQuestions();d.close();renderQuestions()}}
function start(){tilt.reset();if(!canStart()){if(view!=='home')go('home');camStatus(!cameraReady?'① Bật camera để bắt đầu.':!modelReady?'Đang chuẩn bị nhận diện khuôn mặt…':'② Nhấn HIỆU CHỈNH trước khi bắt đầu.');return}if(!questions.length){go('questions');return toast('Hãy thêm ít nhất một câu hỏi trước khi chơi.')}round=questions.map(q=>({...q}));if(settings.shuffle)for(let i=round.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[round[i],round[j]]=[round[j],round[i]]}cancelCelebration();rewardPlan=buildRewardPlan(round.length);earnedRewards=[];index=0;score=0;locked=false;awaitingCenter=false;feedback='';selected=-1;view='play';render();prepareQuestionInput();unlockSound();if(musicEnabled&&musicUrl){audio.currentTime=0;playMusic()}startTimer();window.scrollTo(0,0)}
function journey(){return `<div class="magic-journey" aria-label="Hành trình Lọ Lem đến gặp Hoàng tử"><div id="journey-lane"><div class="track"><div id="journey-fill" class="fill"></div></div>${visibleCheckpoints(round.length).map(step=>`<span class="magic-item" data-step="${step}" style="left:${step/round.length*100}%" title="${esc(rewardPlan[step-1].label)}"><span>${rewardPlan[step-1].icon}</span></span>`).join('')}<span id="reward-marker" class="reward-marker" hidden></span><span id="princess-walker" class="princess-walker"><img src="./assets/princess-walker.webp" alt="Lọ Lem chibi đang trên hành trình"></span><span id="prince-goal" class="prince-goal" role="img" aria-label="Hoàng tử đang chờ Lọ Lem">🤴</span><span class="goal-label">HOÀNG TỬ</span></div></div>`}


function updateJourney(good=false){
  const count=earnedRewards.length,progress=count/round.length,lane=$('#journey-lane');if(!lane)return;
  $('#journey-fill').style.width=100*progress+'%';
  const walker=$('#princess-walker');walker.style.transform=`translateX(${lane.clientWidth*progress}px)`;walker.title=`Đã nhận ${count}/${round.length} phần thưởng`;walker.classList.toggle('walking',good);
  const marker=$('#reward-marker');marker.hidden=!count;marker.style.left=100*progress+'%';marker.textContent=count?earnedRewards[count-1].icon:'';marker.title=count?earnedRewards[count-1].label:'';
  document.querySelectorAll('.magic-item').forEach(el=>{const step=Number(el.dataset.step);el.classList.toggle('earned',step<=count);el.classList.toggle('near-princess',count>0&&Math.abs(step/round.length-progress)<.055);el.classList.toggle('magic-burst',good&&step===count)});
}


function renderPlay(){const q=round[index];app.innerHTML=`<div class="play-top"><div class="play-brand">${logo()}<span>CỖ XE THẦN TIÊN</span></div><span class="badge">Câu <span id="question-count">${index+1}/${round.length}</span></span><div class="play-actions"><button class="icon-button" data-action="toggle-music" id="music-toggle" title="Bật / tắt nhạc nền" aria-label="Bật / tắt nhạc nền"></button><button class="icon-button" data-action="toggle-effects" id="effects-toggle" title="Bật / tắt hiệu ứng" aria-label="Bật / tắt hiệu ứng"></button><button class="icon-button" data-action="fullscreen" title="Toàn màn hình" aria-label="Toàn màn hình">${icon('expand')}</button><button class="icon-button" data-action="home" title="Về trang chủ" aria-label="Về trang chủ">${icon('home')}</button></div><span class="badge score">⭐ <span id="score">${score}</span></span></div>${journey()}<div class="play-field"><section class="question-card"><div class="question-caption">CÂU HỎI ${settings.seconds?'· <span id="timer"></span>':''}</div><div class="text-box"><div class="prompt fit-text" id="prompt">${esc(q.text)}</div></div></section><div class="choices-row"><button class="answer" id="left-answer" data-answer="0" aria-label="Đáp án bên trái: ${esc(q.left)}"><span class="text-box"><span class="value fit-text">${esc(q.left)}</span></span><svg class="hold-ring" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><rect x="2" y="2" width="96" height="96" rx="10" pathLength="100"/></svg></button>${mirror()}<button class="answer right" id="right-answer" data-answer="1" aria-label="Đáp án bên phải: ${esc(q.right)}"><span class="text-box"><span class="value fit-text">${esc(q.right)}</span></span><svg class="hold-ring" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><rect x="2" y="2" width="96" height="96" rx="10" pathLength="100"/></svg></button></div></div><div class="play-bottom"><div id="feedback" class="feedback" aria-live="polite"></div><div class="camera-info"><div class="camera-messages"><strong id="camera-status">${cameraState==='on'?'Đưa đầu về giữa để sẵn sàng':'Bật camera để mở gương thần tiên'}</strong><span id="camera-detail">Chạm đáp án hoặc dùng phím ← → cũng được nhé!</span></div>${cameraControls()}</div></div>`;if(stream){$('#video').srcObject=stream;$('#video').play().catch(()=>{})}updateAudioButtons();updateJourney();updateCameraUI();queueFit()}
function updateQuestion(){const q=round[index];$('#question-count').textContent=`${index+1}/${round.length}`;$('#prompt').textContent=q.text;['left','right'].forEach((s,i)=>{const b=$('#'+s+'-answer');b.querySelector('.value').textContent=q[s];b.classList.remove('correct','wrong','holding','celebrating-answer');b.style.removeProperty('--answer-zoom');b.setAttribute('aria-label','Đáp án bên '+(i===0?'trái: ':'phải: ')+q[s])});$('#feedback').textContent='';clearHold();prepareQuestionInput();queueFit();startTimer()}
function setAnswerAvailability(){document.querySelectorAll('.answer').forEach(b=>b.disabled=locked)}
function prepareQuestionInput(){
  awaitingCenter=inputMode==='tilt'&&!(hasFace&&tilt.state==='CENTER'&&Math.abs(tilt.smoothed??90)<=tilt.config.center);locked=awaitingCenter;
  if(awaitingCenter){tilt.waitForCenter();camStatus('Giữ đầu ở giữa để sẵn sàng nhé!')}
  setAnswerAvailability();
}

function startTimer(){clearInterval(timer);remaining=settings.seconds;if(!remaining)return;if($('#timer'))$('#timer').textContent=remaining+'s';timer=setInterval(()=>{if(view!=='play'||locked||calibrating||cameraState==='loading'||(inputMode==='tilt'&&(!hasFace||!calibrated))||document.hidden)return;remaining--;if($('#timer'))$('#timer').textContent=remaining+'s';if(remaining<=0)answer(-1)},1000)}
function cancelCelebration(){celebrationEpoch++;celebrationTimers.forEach(clearTimeout);celebrationTimers=[];$('#reward-stage')?.remove();clearTimeout(advance)}
function celebrationLater(fn,ms){const epoch=celebrationEpoch;celebrationTimers.push(setTimeout(()=>{if(epoch===celebrationEpoch&&view==='play')fn()},ms))}
function advanceQuestion(){index++;if(index>=round.length)finish();else updateQuestion()}
function showReward(reward){
  const stage=document.createElement('div');stage.id='reward-stage';stage.className='reward-stage';stage.setAttribute('role','status');stage.innerHTML=`<div class="reward-panel"><span class="reward-spark reward-spark-a">✦</span><span class="reward-symbol">${reward.icon}</span><span class="reward-spark reward-spark-b">✦</span><strong class="reward-label">${esc(reward.label)}</strong><span class="reward-subtitle">Một món đồ phép thuật cho Lọ Lem!</span></div>`;app.append(stage);
}
function flyReward(){const stage=$('#reward-stage'),symbol=stage?.querySelector('.reward-symbol'),lane=$('#journey-lane');if(!symbol||!lane)return;const from=symbol.getBoundingClientRect(),to=lane.getBoundingClientRect(),x=to.left+to.width*(earnedRewards.length+1)/round.length,y=to.top+to.height*.72;stage.style.setProperty('--fly-x',`${x-from.left-from.width/2}px`);stage.style.setProperty('--fly-y',`${y-from.top-from.height/2}px`);stage.classList.add('reward-flying')}
function answer(side){
  if(view!=='play'||locked)return;
  locked=true;awaitingCenter=false;tilt.waitForCenter();clearInterval(timer);cancelCelebration();
  const q=round[index],good=side===q.correct,reward=rewardPlan[index];if(good)score++;
  $('#score').textContent=score;clearHold();
  ['left','right'].forEach((s,i)=>{const b=$('#'+s+'-answer');b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===side)b.classList.add('wrong')});
  $('#feedback').textContent=good?'✓ CHÍNH XÁC! Lọ Lem nhận được một phép màu!':side<0?'⏱ Hết giờ! Thử tiếp ở câu sau nhé!':'✕ CHƯA ĐÚNG! Thử tiếp ở câu sau nhé!';effect(good);
  if(!good){celebrationLater(()=>{earnedRewards.push(reward);updateJourney(true)},850);celebrationLater(advanceQuestion,1800);return}
  const chosen=$('#'+(side===0?'left':'right')+'-answer'),value=chosen.querySelector('.value'),rect=value.getBoundingClientRect();
  const center=rect.left+rect.width/2,maxWidth=2*Math.min(center-4,window.innerWidth-center-4);chosen.style.setProperty('--answer-zoom',String(Math.max(1,Math.min(1.5,maxWidth/Math.max(rect.width,1)))));chosen.classList.add('celebrating-answer');
  celebrationLater(()=>showReward(reward),500);
  celebrationLater(flyReward,1100);
  celebrationLater(()=>{$('#reward-stage')?.remove();earnedRewards.push(reward);updateJourney(true)},1700);
  celebrationLater(advanceQuestion,2400);
}


function finish(){cancelCelebration();clearInterval(timer);audio.pause();locked=true;const lane=$('#journey-lane');if(!lane){showFinale();return}lane.classList.add('journey-complete');const stage=document.createElement('div');stage.id='final-magic';stage.className='final-magic';stage.setAttribute('aria-live','polite');stage.innerHTML='<strong>✨ LỌ LEM ĐÃ GẶP HOÀNG TỬ! ✨</strong><span>💖</span>';app.append(stage);effect(true);setTimeout(()=>stage.classList.add('transforming'),1050);setTimeout(showFinale,1950)}
function showFinale(){stopCamera();view='end';render()}
function renderEnd(){app.innerHTML=`<section class="end royal-finale"><div class="finale-shade"></div><div class="finale-heading"><div class="eyebrow">✨ CỖ XE THẦN TIÊN ✨</div><h1>Lọ Lem đã gặp Hoàng tử!</h1><p>Phép màu đã đưa hai người đến bên nhau.</p></div><div class="finale-summary"><div class="stats"><div class="stat">✅ Đúng<strong>${score}</strong></div><div class="stat">❌ Sai<strong>${round.length-score}</strong></div><div class="stat">🏆 Điểm<strong>${score}/${round.length}</strong></div></div><div class="end-buttons">${btn('CHƠI LẠI','start','refresh','primary')}${btn('TRANG CHỦ','home','home')}</div></div></section>`;const c=document.createElement('div');c.className='sparkles finale-sparkles';c.innerHTML=Array.from({length:28},(_,i)=>`<span style="left:${Math.random()*100}%;animation-delay:${Math.random()}s">${['⭐','✨','💖','👑'][i%4]}</span>`).join('');app.append(c);setTimeout(()=>c.remove(),6000)}
function unlockSound(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}}
function effect(good){if(!settings.effects)return;unlockSound();if(!audioCtx)return;[good?523:260,good?659:220,good?784:196].forEach((hz,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.13;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.1,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.18);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.2)})}
async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('royal-music',1);r.onupgradeneeded=()=>r.result.createObjectStore('tracks');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function musicStore(value,remove=false){db??=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction('tracks','readwrite'),s=t.objectStore('tracks');remove?s.delete('background'):s.put(value,'background');t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
function setMusic(blob,name){audio.pause();if(musicUrl)URL.revokeObjectURL(musicUrl);musicUrl=URL.createObjectURL(blob);audio.src=musicUrl;audio.volume=settings.volume;audio.loop=settings.loop;musicName=name}
async function restoreMusic(){try{db=await openDB();const t=db.transaction('tracks'),r=t.objectStore('tracks').get('background');r.onsuccess=()=>{if(r.result){setMusic(r.result.blob,r.result.name);if(view==='settings')renderSettings()}}}catch{}}
async function playMusic(){if(!musicUrl)return toast('Chưa có nhạc. Thêm bài nhạc trong Thiết lập.');try{audio.volume=settings.volume;audio.loop=settings.loop;await audio.play()}catch{toast('Nhấn nút Nhạc để phát, hoặc chọn file âm thanh khác.')}}
async function uploadMusic(file){if(!file)return;if(file.size>80*1024*1024)return toast('Hãy chọn bài nhạc nhỏ hơn 80 MB.');if(!/\.(mp3|wav|m4a|aac|ogg|webm)$/i.test(file.name)&&!file.type.startsWith('audio/'))return toast('Vui lòng chọn file âm thanh.');const url=URL.createObjectURL(file),test=new Audio();test.preload='metadata';const ok=await new Promise(resolve=>{const timeout=setTimeout(()=>resolve(false),12000);test.onloadedmetadata=()=>{clearTimeout(timeout);resolve(true)};test.onerror=()=>{clearTimeout(timeout);resolve(false)};test.src=url});URL.revokeObjectURL(url);if(!ok)return toast('Trình duyệt không đọc được file này. Hãy thử MP3 hoặc WAV.');setMusic(file,file.name);musicEnabled=true;try{await musicStore({blob:file,name:file.name});toast('Đã lưu nhạc nền trên thiết bị này.')}catch{toast('Nhạc dùng được trong phiên này nhưng chưa lưu được trên thiết bị.')}if(view==='settings')renderSettings()}
function updateAudioButtons(){const m=$('#music-toggle'),e=$('#effects-toggle');if(m){m.style.opacity=musicEnabled?'1':'.5';m.setAttribute('aria-pressed',musicEnabled);m.title='Nhạc nền: '+(musicEnabled?'BẬT':'TẮT');m.innerHTML=icon('music')+`<span class="button-label"><span class="sound-kind">Nhạc: </span>${musicEnabled?'BẬT':'TẮT'}</span>`}if(e){e.style.opacity=settings.effects?'1':'.5';e.setAttribute('aria-pressed',settings.effects);e.title='Hiệu ứng: '+(settings.effects?'BẬT':'TẮT');e.innerHTML=icon('volume')+`<span class="button-label"><span class="sound-kind">Hiệu ứng: </span>${settings.effects?'BẬT':'TẮT'}</span>`}}
function camStatus(title,detail=''){updateCameraUI();if($('#camera-status'))$('#camera-status').textContent=title;if($('#camera-detail'))$('#camera-detail').textContent=detail}
function withTimeout(promise,ms,message){let timeout;return Promise.race([promise,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error(message)),ms)})]).finally(()=>clearTimeout(timeout))}
async function loadDetector(){
  if(landmarker)return landmarker;
  if(!modelLoadPromise)modelLoadPromise=(async()=>{const {FaceLandmarker,FilesetResolver}=await import('./assets/vision.mjs');const vision=await FilesetResolver.forVisionTasks('./assets/wasm');return FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'./assets/face_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numFaces:1,minFaceDetectionConfidence:.5,minFacePresenceConfidence:.5,minTrackingConfidence:.5})})().then(detector=>{landmarker=detector;return detector}).finally(()=>{modelLoadPromise=null});
  return modelLoadPromise;
}
async function enableCamera(){
  if(cameraState==='loading')return;
  if(cameraReady&&modelReady){stopCamera();if(view==='home')renderHome();else camStatus('Camera đã tắt. Nhấn BẬT CAMERA để tiếp tục.');return}
  stopCamera();cameraMessage='';calibrationFailed=false;const epoch=++cameraEpoch;cameraState='loading';camStatus('① Cho phép sử dụng camera khi trình duyệt hỏi.');
  try{
    if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera cần kết nối HTTPS và trình duyệt hỗ trợ.');
    const requested=navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:640},height:{ideal:480}}}).then(s=>{if(epoch!==cameraEpoch){s.getTracks().forEach(t=>t.stop());throw Error('Camera request cancelled')}return s});
    const s=await withTimeout(requested,30000,'Chưa nhận được quyền camera. Hãy cho phép rồi thử lại.');
    if(epoch!==cameraEpoch||!['home','play'].includes(view)){s.getTracks().forEach(t=>t.stop());return}
    stream=s;const video=$('#video');video.hidden=false;$('#camera-placeholder').hidden=true;video.srcObject=stream;
    await withTimeout(video.play(),10000,'Chưa phát được camera. Hãy thử lại camera.');
    if(epoch!==cameraEpoch)return;
    cameraReady=true;camStatus('① Camera đã mở. Đang tải nhận diện khuôn mặt…');
    const detector=await withTimeout(loadDetector(),25000,'Chưa thể nhận diện khuôn mặt. Hãy thử lại.');
    if(epoch!==cameraEpoch)return;
    landmarker=detector;modelReady=true;cameraState='on';detectFailures=0;lastVideo=-1;lastFaceAt=0;lastFrame=0;
    stream.getVideoTracks?.().forEach(track=>track.addEventListener('ended',()=>{if(epoch===cameraEpoch){stopCamera();cameraMessage='Camera đã ngắt. Hãy thử lại camera.';camStatus(cameraMessage)}},{once:true}));
    camStatus('② Nhấn HIỆU CHỈNH, rồi nhìn thẳng vào gương.');startDetectionLoop();
  }catch(error){
    if(epoch!==cameraEpoch)return;stopCamera();cameraMessage=error.name==='NotAllowedError'?'Camera chưa được bật. Hãy cho phép sử dụng camera rồi thử lại.':error.message||'Chưa thể nhận diện khuôn mặt. Hãy thử lại.';camStatus(cameraMessage);
  }
}

function stopCamera(){clearTimeout(calibrationTimer);cameraReady=false;modelReady=false;cameraEpoch++;loopEpoch++;cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());stream=null;cameraState='off';hasFace=false;calibrated=false;calibrating=false;detecting=false;lastFaceAt=0;tilt.reset();poseCalibration.reset();clearHold();const video=$('#video');if(video){video.srcObject=null;video.hidden=true}if($('#camera-placeholder'))$('#camera-placeholder').hidden=false}

function calibrate(){
  if(!cameraReady||!modelReady)return;
  clearTimeout(calibrationTimer);calibrated=false;calibrationFailed=false;cameraMessage='';clearHold();calibrating=true;poseCalibration.reset();tilt.reset();
  camStatus('Nhìn thẳng vào gương nhé!');const epoch=cameraEpoch;
  calibrationTimer=setTimeout(()=>{if(epoch!==cameraEpoch||!calibrating)return;calibrating=false;calibrationFailed=true;camStatus(hasFace?'Giữ đầu yên một chút, rồi nhấn THỬ LẠI nhé!':'👸 Hãy đưa khuôn mặt vào giữa gương nhé!')},8000);
}

function startDetectionLoop(){cancelAnimationFrame(raf);const epoch=++loopEpoch;const tick=()=>{if(epoch!==loopEpoch||!['home','play'].includes(view)||cameraState!=='on')return;raf=requestAnimationFrame(tick);loopCamera()};tick()}
function missingFace(now){poseCalibration.add(null,now);const state=tilt.update(null,now,{blocked:locked});if(!lastFaceAt||now-lastFaceAt>=TILT_CONFIG.graceMs){hasFace=false;clearHold();camStatus('😊 Đưa khuôn mặt vào giữa gương nhé!')}else if(view==='play')paintHold(state)}
function loopCamera(){
  if(!['home','play'].includes(view)||cameraState!=='on'||detecting||document.hidden)return;
  const now=performance.now(),v=$('#video');
  if(!v||now-lastFrame<TILT_CONFIG.frameMs)return;
  if(v.readyState<2||v.currentTime===lastVideo){if(lastFaceAt&&now-lastFaceAt>TILT_CONFIG.graceMs)missingFace(now);return}
  lastVideo=v.currentTime;lastFrame=now-((now-lastFrame)%TILT_CONFIG.frameMs);detecting=true;
  try{
    if(!landmarker){camStatus('Đang tải nhận diện…');return}
    const result=landmarker.detectForVideo(v,now),angle=headRoll(result.faceLandmarks?.[0],v.videoWidth,v.videoHeight);
    if(angle===null){missingFace(now);return}
    hasFace=true;detectFailures=0;lastFaceAt=now;rawAngle=angle;
    if(calibrating){const neutral=poseCalibration.add(angle,now);if(neutral!==null){clearTimeout(calibrationTimer);baseline=neutral;calibrating=false;calibrated=true;calibrationFailed=false;tilt.reset();camStatus('✨ Đã sẵn sàng! Bắt đầu hành trình thôi!')}return}
    if(!calibrated){if(!calibrationFailed)camStatus('② Nhấn HIỆU CHỈNH, rồi nhìn thẳng vào gương.');return}
    if(view==='home'){camStatus('✨ Đã sẵn sàng! Bắt đầu hành trình thôi!');return}
    processAngle(angle-baseline,now);
  }catch(error){
    if(now-lastDetectError>2000||!lastDetectError){console.warn('Face detection frame failed; retrying next frame.',error);lastDetectError=now}
    detectFailures++;if(detectFailures>=12){stopCamera();landmarker?.close?.();landmarker=null;cameraMessage='Chưa thể nhận diện khuôn mặt. Hãy thử lại.';camStatus(cameraMessage)}else missingFace(now);
  }finally{detecting=false}
}

function processAngle(angle,now){
  tilt.config.enter=settings.threshold;tilt.config.exit=Math.min(TILT_CONFIG.exit,settings.threshold-2);tilt.config.center=Math.min(TILT_CONFIG.center,settings.threshold-3);tilt.config.holdMs=settings.hold;
  const state=tilt.update(angle,now,{blocked:locked||document.hidden});if(awaitingCenter&&state.state==='CENTER'){awaitingCenter=false;locked=false;setAnswerAvailability()}paintHold(state);
  if(state.confirmed!==null){answer(state.confirmed);return}
  if(locked)return;
  if(state.state==='WAIT_FOR_CENTER')camStatus('Giữ đầu ở giữa một chút nhé!');
  else if(state.side>=0)camStatus(state.side===0?'← Đang chọn bên TRÁI':'Đang chọn bên PHẢI →');
  else camStatus('Sẵn sàng! Nghiêng đầu để chọn');
}


function clearHold(){const mirror=$('.magic-mirror');mirror?.classList.remove('lean-left','lean-right','mirror-holding');mirror?.style.setProperty('--hold','0');document.querySelectorAll('.answer').forEach(el=>{el.classList.remove('holding');el.style.setProperty('--hold','0');el.removeAttribute('data-hold')})}
function paintHold(state){
  if(locked||document.hidden||calibrating||state.side<0){clearHold();return}
  const mirror=$('.magic-mirror');mirror?.classList.toggle('lean-left',state.side===0);mirror?.classList.toggle('lean-right',state.side===1);mirror?.classList.add('mirror-holding');mirror?.style.setProperty('--hold',String(state.progress));
  document.querySelectorAll('.answer').forEach((el,i)=>{el.classList.toggle('holding',i===state.side);el.style.setProperty('--hold',i===state.side?String(state.progress):'0');el.setAttribute('data-hold',i===state.side?Math.round(state.progress*100)+'%':'')});
}

let fitObserver=null,fitFrame=0;
function queueFit(){cancelAnimationFrame(fitFrame);fitFrame=requestAnimationFrame(()=>{fitObserver?.disconnect();if(view!=='play')return;fitObserver??=new ResizeObserver(()=>fitText());document.querySelectorAll('.text-box').forEach(el=>fitObserver.observe(el));fitText()})}
function fitText(){if(view!=='play')return;updateJourney();document.querySelectorAll('.fit-text').forEach(el=>{const box=el.parentElement,w=box.clientWidth,h=box.clientHeight;if(!w||!h)return;let low=5,high=Math.min(el.id==='prompt'?180:160,h*.85),best=low;for(let i=0;i<13;i++){const n=(low+high)/2;el.style.fontSize=n+'px';if(el.scrollWidth<=w&&el.scrollHeight<=h){best=n;low=n}else high=n}el.style.fontSize=Math.floor(best)+'px'})}
window.addEventListener('resize',queueFit);window.visualViewport?.addEventListener('resize',queueFit);document.fonts?.ready.then(queueFit);

document.addEventListener('click',async e=>{const v=e.target.closest('[data-view]');if(v){audio.pause();go(v.dataset.view);return}const ans=e.target.closest('[data-answer]');if(ans){answer(Number(ans.dataset.answer));return}const ed=e.target.closest('[data-edit]');if(ed)return editQuestion(Number(ed.dataset.edit));const cp=e.target.closest('[data-copy]');if(cp){if(questions.length>=300)return toast('Tối đa 300 câu hỏi.');const i=Number(cp.dataset.copy);questions.splice(i+1,0,{...questions[i],id:questionId()});saveQuestions();renderQuestions();return}const del=e.target.closest('[data-delete]');if(del){if(confirm('Xóa câu hỏi này?')){questions.splice(Number(del.dataset.delete),1);saveQuestions();renderQuestions()}return}const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;switch(a){case'start':start();break;case'home':go('home');break;case'add':editQuestion();break;case'save-settings':saveSettings();toast('Đã lưu thiết lập.');break;case'upload-music':$('#music-file').click();break;case'preview-music':playMusic();break;case'pause-music':audio.pause();break;case'delete-music':audio.pause();audio.removeAttribute('src');audio.load();if(musicUrl)URL.revokeObjectURL(musicUrl);musicUrl='';musicName='';try{await musicStore(null,true)}catch{toast('Chưa xóa được nhạc đã lưu.')}renderSettings();break;case'toggle-music':musicEnabled=!musicEnabled;musicEnabled?playMusic():audio.pause();updateAudioButtons();break;case'toggle-effects':settings.effects=!settings.effects;saveSettings();updateAudioButtons();break;case'mode-touch':inputMode='touch';cameraMessage='';stopCamera();renderHome();break;case'mode-tilt':inputMode='tilt';renderHome();break;case'camera':inputMode='tilt';enableCamera();break;case'calibrate':case'retry-calibration':calibrate();break;case'fullscreen':try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Trình duyệt này chưa hỗ trợ toàn màn hình.')}catch{toast('Không bật được toàn màn hình trong trình duyệt này.')}break;case'export':{const blob=new Blob([JSON.stringify({title:'Cỗ xe thần tiên',questions},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='bo-cau-hoi.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);break}case'import':$('#import-file').click();break;case'sample':if(confirm('Thay bộ câu hỏi hiện tại bằng 10 câu Toán mẫu?')){questions=defaults.map(x=>({...x}));saveQuestions();renderQuestions()}break}});
document.addEventListener('input',e=>{const id=e.target.id;if(['volume','threshold'].includes(id)){settings[id]=Number(e.target.value)/(id==='volume'?100:1);$('#'+id+'-value').textContent=e.target.value+(id==='volume'?'%':'°');saveSettings()}});
document.addEventListener('change',e=>{const id=e.target.id;if(['loop','effects','shuffle'].includes(id)){settings[id]=e.target.checked;saveSettings()}if(['seconds','hold'].includes(id)){settings[id]=Number(e.target.value);saveSettings()}});
$('#music-file').onchange=e=>{uploadMusic(e.target.files[0]);e.target.value=''};
$('#import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>2*1024*1024)throw Error();const data=JSON.parse(await f.text()),q=Array.isArray(data)?data:data.questions;if(!validQuestions(q)||!q.length)throw Error();if(confirm(`Nhập ${q.length} câu và thay bộ câu hỏi hiện tại?`)){questions=q.map(x=>({...x,id:questionId()}));saveQuestions();renderQuestions();toast('Đã nhập bộ câu hỏi.')}}catch{toast('File chưa hợp lệ. Hãy dùng file JSON được xuất từ trò chơi.')}};
document.addEventListener('keydown',e=>{if(view==='play'&&!e.repeat&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();answer(e.key==='ArrowLeft'?0:1)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.pause();tilt.reset();poseCalibration.reset();clearHold()}else if(view==='play'&&musicEnabled&&musicUrl)audio.play().catch(()=>toast('Nhấn nút Nhạc để phát tiếp.'))});
window.addEventListener('pagehide',()=>{audio.pause();stopCamera()});
document.querySelectorAll('[data-icon]').forEach(b=>b.innerHTML=icon(b.dataset.icon)+b.innerHTML);$('.brand').onclick=e=>{e.preventDefault();go('home')};saveSettings();restoreMusic();render();
